ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}

RUN mkdir /usr/share/kibana/elk-ssl/

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
